### PR TITLE
fix type instance conflict

### LINKED ISSUE #1: type-operators-0.2.0.0 does not build with GHC 9.4
```console
$ cabal build
...
Build profile: -w ghc-9.4.4 -O1
...
Building library for type-operators-0.2.0.0..
[1 of 1] Compiling Control.Type.Operator ( Control/Type/Operator.hs, /Users/abel/tmp/type-operators-0.2.0.0/dist-newstyle/build/x86_64-osx/ghc-9.4.4/type-operators-0.2.0.0/build/Control/Type/Operator.o, /Users/abel/tmp/type-operators-0.2.0.0/dist-newstyle/build/x86_64-osx/ghc-9.4.4/type-operators-0.2.0.0/build/Control/Type/Operator.dyn_o )

Control/Type/Operator.hs:97:15: error:
    Conflicting family instance declarations:
      [] <+> _ = () :: Constraint
        -- Defined at Control/Type/Operator.hs:97:15
      forall {k} {c :: k -> Constraint} {a :: k} {as :: [k]}.
        c <+> (a : as) = (c a, c <+> as)
          -- Defined at Control/Type/Operator.hs:99:15
   |
97 | type instance (<+>) [] _ = (() :: Constraint)
   |               ^^^^^
```
Lifted from:
- https://github.com/commercialhaskell/stackage/issues/6773

In my role as Hackage Trustee, I restricted `base` to `<4.17` on hackage: https://hackage.haskell.org/package/type-operators-0.2.0.0/revisions/

### PR DESCRIPTION
**Pull request by GuillaumedeVolpiano**
Fixes #1 
Not sure it's the best way to do it, but for now, it's the only one I've found.

### CODE REVIEW

**Comment by habibalamin** [comment]
Take this with a grain of salt, because I only have a thin grasp of type-level programming, but I think this makes more sense:

```diff
type family (<+>) (a :: k1) (b :: k2) :: Constraint
type instance (<+>) _ [] = (() :: Constraint)
type instance (<+>) [] _ = (() :: Constraint)
-type instance (<+>) (c ': cs) (a :: Type) = (c a, a <+> cs)
-type instance (<+>) c (a ': as) = (c a, c <+> as)
+type instance (<+>) (c ': cs) (a ': as) = (c a, cs <+> a, c <+> as)
infixl 9 <+>
```

If _either_ are empty, it's already bailed, so we know both have at least one element, so we apply the first element of each list to each other, then each element of the rest of the first list to the first element of the second list and each element of the rest of the second list to the first element of the first list.

I dunno why GHC is saying `[] <+> _` conflicts with `c <+> (a ': as)`, but ironically, I think the added pattern match for `(c ': cs) <+> (a ': as)` is covered by the existing `(c ': cs) <+> a`, which GHC _doesn't_ fail the build for. So I remove that line as well (it builds both with and without that line removed, but I dunno if the second match will be hit if we don't remove the first line).

@Shou are we off track here?

Edit: I guess each element of both lists has to also be applied to each other, so:

```diff
-type instance (<+>) (c ': cs) (a ': as) = (c a, cs <+> a, c <+> as)
+type instance (<+>) (c ': cs) (a ': as) = (c a, cs <+> a, c <+> as, cs <+> as)
```

**Comment by habibalamin** [comment]
Hey, @GuillaumedeVolpiano, since you already have the repo forked, if you think my solution makes more sense, would you go ahead and apply it on your PR?; I can't be bothered to make another PR.

**Comment by habibalamin** [comment]
How would you even write type-level tests for type-level functions? Could this library do with a test suite?
