### ISSUE TITLE
type-operators-0.2.0.0 does not build with GHC 9.4

### ISSUE THREAD

**Issue by andreasabel** [Shou/type-operators#1]
```console
$ cabal build
...
Build profile: -w ghc-9.4.4 -O1
...
Building library for type-operators-0.2.0.0..
[1 of 1] Compiling Control.Type.Operator ( Control/Type/Operator.hs, /Users/abel/tmp/type-operators-0.2.0.0/dist-newstyle/build/x86_64-osx/ghc-9.4.4/type-operators-0.2.0.0/build/Control/Type/Operator.o, /Users/abel/tmp/type-operators-0.2.0.0/dist-newstyle/build/x86_64-osx/ghc-9.4.4/type-operators-0.2.0.0/build/Control/Type/Operator.dyn_o )

Control/Type/Operator.hs:97:15: error:
    Conflicting family instance declarations:
      [] <+> _ = () :: Constraint
        -- Defined at Control/Type/Operator.hs:97:15
      forall {k} {c :: k -> Constraint} {a :: k} {as :: [k]}.
        c <+> (a : as) = (c a, c <+> as)
          -- Defined at Control/Type/Operator.hs:99:15
   |
97 | type instance (<+>) [] _ = (() :: Constraint)
   |               ^^^^^
```
Lifted from:
- https://github.com/commercialhaskell/stackage/issues/6773

In my role as Hackage Trustee, I restricted `base` to `<4.17` on hackage: https://hackage.haskell.org/package/type-operators-0.2.0.0/revisions/
